baseURL = "https://mylyapp.tech/"
title = "myly - School Management App, School ERP"
theme = "navigator-hugo"
summaryLength = 10
publishDir = "public"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true



# Site Menus
[menu]
    

   
      
    
